name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pipenv
    - name: Install pipenv dependencies
      run: |
        pipenv install
    - name: Analysing the code with pylint
      run: |
        # Stop run if there are linting errors
        pipenv run lint
    - name: Test with pytest with coverage
      run: |
        pipenv run tests-cov
    - name: Generate coverage report
      run: |
        pipenv run cov-report
