name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --user pipenv
        pipenv install --dev
    - name: Analysing the code with pylint
      run: |
        # Stop run if there are linting errors
        pipenv run pylint `find . \( -iname '*.py' \)`
    - name: Test with pytest with coverage
      run: |
        pipenv run coverage run -m pytest
    - name: Publish coverage to html
      run: |
        pipenv coverage report -m 