name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install coverage
        pip install pytest
        pip install python-dotenv
        pipenv install
    - name: Analysing the code with pylint
      run: |
        # Stop run if there are linting errors
        pylint `find . \( -iname '*.py' \)`
    - name: Test with pytest with coverage
      run: |
        coverage run -m pytest
    - name: Publish coverage to html
      run: |
        coverage report -m 